### ISSUE TITLE
Googling for my VirtualBox error and found your blog!

### ISSUE THREAD

**Issue by nathanhleung** [blimmer/benlimmer.com#11]
Hey, just wanted to say that I came across your [post](https://benlimmer.com/2017/04/23/macos-sierra-virtualbox-10-12-4/) when looking up my Sierra/VirtualBox error - thanks for saving me a lot of time!

Unfortunately, though, I don't have access to a previous version of the Sierra installer. :(

Would you by any chance have a working previous version of Sierra you could shoot my way?

No worries if you don't, but let me know.
Nathan

**Comment by blimmer** [comment]
Unfortunately there's no officially supported way to get an older installer. I've heard that some people have had luck finding the installer with google search terms like "macOS sierra 10.12.3 installer". If anyone were to theoretically find an installer this way, it would be wise to make sure they are not breaking any licensing agreements and check the checksum with the checksums linked in the blog post. I'm not suggesting or implying use BitTorrent or like technology.

Sorry, that's about all I've got on this topic. Good luck!
