### ISSUE TITLE
Update the Datadog + pino-lambda instructions

### ISSUE THREAD

**Issue by paambaati** [blimmer/benlimmer.com#42]
First, thank you so much for writing https://benlimmer.com/2020/10/23/make-pino-log-messages-appear-with-the-correct-status-in-datadog/

We were struggling with figuring this out!

For configuring the log preprocessor in Datadog, it looks like things have changed, and I see new input fields that I'm not sure how to configure –

<img width="1535" alt="Screengrab 2021-12-08 at 19 44 50@2x" src="https://user-images.githubusercontent.com/5381764/145223353-35e854ee-6ce8-4a13-a173-bf4f2476174c.png">

If you're still using Datadog, perhaps editing that same pipeline would now show you values I can then copy? Would you mind updating the post with that information?

**Comment by blimmer** [comment]
I'm glad you got it figured out! Thanks for the kind words and I'm glad this blog post helped you out :smile:
