### ISSUE TITLE
Graphql codegen for Github API

### ISSUE THREAD

**Issue by Hacksore** [blimmer/benlimmer.com#49]
Hi Ben,

I tried following [your blog post](https://benlimmer.com/2020/05/16/adding-typescript-types-github-graphql-api/) and ran into some issues trying to get codegen working.

Getting blocked but there very well could be a simple bug that I am overlooking and any help is greatly appreciated.

https://github.com/Hacksore/test-github-graphql

**Comment by Hacksore** [comment]
Was able to get it to generate with some help from a few folks. 

I really want to get a typesafe query working in nodejs and have "solution" but it is rather janky.

**Comment by blimmer** [comment]
Hey @Hacksore - sorry you ran into issues with the blog post. It looks like a few things have changed since I last refreshed the post. Please check out #50 and the updated post: https://benlimmer.com/2020/05/16/adding-typescript-types-github-graphql-api/ . I went through all the steps again and confirmed it's working as intended now.

As always, additional feedback and PRs are welcome. I didn't tackle the ESM bits (it still uses ts-node for greater compatibility), but that could be a nice addition to call out in the post.

**Comment by Hacksore** [comment]
@blimmer thanks for updating the blog I'm sure it will be invaluable for the next person who stumbles upon it.

Perhaps it's really a pipe-dream to have a FULLY typesafe query in nodejs land. Seems the frontend has solutions with things like the apollo client.

This is what I have today.
```ts
import { ContributionsCollection } from "./generated/graphql.js";
import { graphql } from "@octokit/graphql";

const graphqlWithAuth = graphql.defaults({
  headers: {
    authorization: `token ${process.env.GITHUB_TOKEN}`,
  },
});

// This works but is super fragile
const GET_USER_CONTRIBUTIONS = `
query GetContributions ($login: String!) {
  user (login: $login){
    contributionsCollection {
      contributionCalendar {
        totalContributions,
        weeks {
          contributionDays {
            contributionCount
          }
        }
      }
    }
  }
}
`;

try {
  console.log("getting data...");
  const res = await graphqlWithAuth<ContributionsCollection>(GET_USER_CONTRIBUTIONS, { login: "Hacksore" });

  console.log("res:", res.user.contributionsCollection.contributionCalendar.totalContributions);
} catch (error: any) {
  console.log("error:", error);
}
```

**Comment by blimmer** [comment]
Based on your comment, I'm assuming you want to type `GET_USER_CONTRIBUTIONS`. If so, the [`typescript-operations`](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations) generator I reference in the blog post could help. That'll make sure your operations are valid, and also type variables and return properties.

Did you try that?

**Comment by Hacksore** [comment]
@blimmer I got it working!

https://github.com/Hacksore/test-github-graphql
